### ISSUE TITLE
Add Github Actions Cron Job

### ISSUE THREAD

**Issue by LuchoBazz** [LuchoBazz/knowledge-core#6]
```yaml
name: Auto Slack Status Set Lunch


on:
  schedule:
    # Runs at 12:30 AM from Monday to Friday
    - cron: '30 17 * * 1-5'

jobs:
  update-slack-status:
    runs-on: ubuntu-latest

    container:
      image: alpine/curl:latest

    steps:
    - name: Update Slack status using curl
      run: |
        current_time=$(date +%s)  # Get the current timestamp
        expiration_time=$((current_time + 3600))  # Expires in 1 hour (3600 seconds)
        
        curl --silent --output /dev/null -X POST https://slack.com/api/users.profile.set \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.INSTALEAP_SLACK_TOKEN }}" \
        -d '{
          "profile": {
            "status_text": "Lunch",
            "status_emoji": ":avocado:",
            "status_expiration": '"$expiration_time"'
          }
        }'
```
